import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createApp} from '../lib/app.mjs';
import {MemoryStore} from '../lib/storage.mjs';
import {hashPassword,digest} from '../lib/security.mjs';
import {quote,termsVersion} from '../lib/catalog.mjs';
const origin='https://mindmorphia-site.vercel.app';
async function fixture(){const store=new MemoryStore();const hash=await hashPassword('Synthetic-testing-2026!');store.state.users=[{id:'a',name:'Cliente A',email:'a@example.invalid',role:'client',password:hash,active:true},{id:'b',name:'Cliente B',email:'b@example.invalid',role:'client',password:hash,active:true},{id:'owner',name:'Responsável',email:'owner@example.invalid',role:'owner',password:hash,active:true},{id:'staff',name:'Equipe restrita',email:'staff@example.invalid',role:'staff',permissions:['requests'],password:hash,active:true}];const env={SITE_URL:origin,BLOB_READ_WRITE_TOKEN:'synthetic',RESEND_API_KEY:'synthetic',EMAIL_FROM:'teste@example.invalid',MERCADOPAGO_ACCESS_TOKEN:'synthetic',MERCADOPAGO_WEBHOOK_SECRET:'synthetic-secret',MERCADOPAGO_COLLECTOR_ID:'123'};const mails=[];const payments=new Map();const preferences=[];const app=createApp({store,env,mailer:async(_e,to,url,label)=>{mails.push({to,url,label});return {id:'synthetic'};},payment:async(_e,path,body)=>{if(path==='/users/me')return payments.get('account')||{id:123,tags:[]};if(body){preferences.push(body);return {id:'preference',collector_id:payments.get('preferenceCollector')||123,init_point:'https://www.mercadopago.com.br/checkout/v1/redirect?pref_id=synthetic'};}return payments.get(path.split('/').pop());}});async function call(path,body,cookie='',extra={}){const r=await app(new Request(origin+'/api'+path,{method:body?'POST':'GET',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})}));let data;try{data=await r.clone().json();}catch{data=await r.clone().text();}return {r,data};}async function login(email='a@example.invalid'){const {r}=await call('/auth/login',{email,password:'Synthetic-testing-2026!'});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}return {store,env,mails,payments,preferences,call,login};}
const orderBody={items:[{id:'impacto',quantity:1}],mode:'deposit',brief:'Projeto de teste sintético',accepted:true,termsVersion,key:'synthetic-request-0001'};
test('preço do servidor, entrada de 50%, cupons e catálogo inválido',async()=>{const f=await fixture();f.store.state.coupons.push({code:'MM10',percent:10,active:true});const q=quote(f.store.state,{...orderBody,coupon:'MM10',total:1});assert.equal(q.total,89730);assert.equal(q.due,44865);assert.equal(q.shipping,0);assert.throws(()=>quote(f.store.state,{items:[{id:'unknown',quantity:1}]}));assert.throws(()=>quote(f.store.state,{items:[{id:'impacto',quantity:0}]}));assert.throws(()=>quote(f.store.state,{...orderBody,coupon:'INVALID'}));});
test('cookie seguro, CSRF e logout revogam consultas',async()=>{const f=await fixture();const c=await f.login();const r=await f.call('/auth/login',{email:'a@example.invalid',password:'Synthetic-testing-2026!'});assert.match(r.r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.match(r.r.headers.get('set-cookie'),/Secure/);assert.equal((await f.call('/requests',{subject:'Teste',description:'Teste'},c,{origin:'https://attacker.invalid'})).r.status,403);await f.call('/auth/logout',{},c);assert.equal((await f.call('/dashboard',null,c)).r.status,401);});
test('clientes não leem projetos, solicitações, notas internas ou arquivos alheios',async()=>{const f=await fixture();const a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');const result=await f.call('/requests',{subject:'Cliente A',description:'Descrição'},a);const id=result.data.request.id;await f.call(`/requests/${id}/message`,{text:'Nota privada',internal:true},o);assert.equal((await f.call(`/requests/${id}/message`,{text:'Invasão'},b)).r.status,404);assert.equal((await f.call('/dashboard',null,b)).data.requests.length,0);assert.equal((await f.call('/dashboard',null,a)).data.requests[0].messages.length,0);const file=await f.call('/files',{requestId:id,name:'teste.txt',type:'text/plain',data:Buffer.from('Sintético').toString('base64')},a);assert.equal(file.r.status,201);assert.equal((await f.call(`/files/${file.data.id}`,null,b)).r.status,404);assert.equal((await f.call(`/files/${file.data.id}`,null,a)).r.status,200);assert.equal((await f.call(`/files/${file.data.id}`)).r.status,401);});
test('permissões limitam equipe e suspensão invalida próxima operação',async()=>{const f=await fixture();const s=await f.login('staff@example.invalid'),o=await f.login('owner@example.invalid');assert.equal((await f.call('/admin/catalog',{name:'X',price:100},s)).r.status,403);assert.equal((await f.call('/admin/team',{id:'staff',permissions:['catalog']},s)).r.status,403);assert.equal((await f.call('/dashboard',null,s)).data.clients.length,0);await f.call('/admin/team',{id:'staff',permissions:[],suspended:true},o);assert.equal((await f.call('/dashboard',null,s)).r.status,401);});
test('orçamento exige titular, versão atual e decisão única registrada',async()=>{const f=await fixture();const a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');const id=(await f.call('/requests',{subject:'Serviço',description:'Ampliação'},a)).data.request.id;await f.call(`/requests/${id}/proposal`,{scope:'Nova página',amount:20000,dueDate:'2026-10-20'},o);const proposalId=(await f.call('/dashboard',null,a)).data.requests[0].proposal.id;assert.equal((await f.call(`/requests/${id}/decision`,{proposalId,decision:'accepted'},b)).r.status,404);assert.equal((await f.call(`/requests/${id}/decision`,{proposalId:'old',decision:'accepted'},a)).r.status,400);assert.equal((await f.call(`/requests/${id}/decision`,{proposalId,decision:'accepted'},a)).r.status,200);assert.equal((await f.call(`/requests/${id}/decision`,{proposalId,decision:'rejected'},a)).r.status,400);});
test('pedido idempotente preserva preço e condições após edição',async()=>{const f=await fixture();const c=await f.login();const first=await f.call('/orders',orderBody,c);const second=await f.call('/orders',{...orderBody,total:1},c);assert.equal(first.data.order.id,second.data.order.id);assert.equal(first.data.order.total,99700);assert.equal(f.store.state.orders.length,1);const owner=await f.login('owner@example.invalid');await f.call('/admin/catalog',{id:'impacto',name:'Impacto',scope:'Novo escopo',price:120000,active:true},owner);assert.equal(f.store.state.orders[0].total,99700);assert.equal((await f.call('/quote',orderBody,c)).data.total,120000);});
test('pagamento valida assinatura, conta, moeda, valor e modo real',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;await f.call(`/orders/${id}/payment`,{},c);assert.equal((await f.call('/webhooks/mercadopago?data.id=123',{},'',{'x-request-id':'rid','x-signature':'ts=1,v1=bad'})).r.status,401);const signature=createHmac('sha256',f.env.MERCADOPAGO_WEBHOOK_SECRET).update('id:123;request-id:rid;ts:1;').digest('hex');const headers={'x-request-id':'rid','x-signature':`ts=1,v1=${signature}`};const p={id:123,collector_id:123,currency_id:'BRL',live_mode:true,external_reference:id,status:'approved',transaction_amount:498.5,date_last_updated:'2026-10-09T01:00:00Z'};f.payments.set('123',{...p,collector_id:999});assert.equal((await f.call('/webhooks/mercadopago?data.id=123',{},'',headers)).r.status,400);f.payments.set('123',p);assert.equal((await f.call('/webhooks/mercadopago?data.id=123',{},'',headers)).r.status,200);assert.equal(f.store.state.orders[0].paid,49850);assert.equal(f.store.state.orders[0].balance,49850);assert.equal(f.store.state.projects.length,1);await f.call('/webhooks/mercadopago?data.id=123',{},'',headers);assert.equal(f.store.state.projects.length,1);assert.equal(f.store.state.orders[0].paid,49850);});
test('cancelamento persiste e pagamento tardio exige análise sem entrega automática',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;await f.call(`/orders/${id}/payment`,{},c);await f.call(`/orders/${id}/cancel`,{},c);assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,400);f.payments.set('123',{id:123,collector_id:123,currency_id:'BRL',live_mode:true,external_reference:id,status:'approved',transaction_amount:498.5,date_last_updated:'2026-10-09T01:00:00Z'});const signature=createHmac('sha256',f.env.MERCADOPAGO_WEBHOOK_SECRET).update('id:123;request-id:rid;ts:1;').digest('hex');await f.call('/webhooks/mercadopago?data.id=123',{},'',{'x-request-id':'rid','x-signature':`ts=1,v1=${signature}`});assert.equal(f.store.state.orders[0].status,'cancelamento_em_analise');assert.equal(f.store.state.projects.length,0);});
test('recuperação tem token de uso único e revoga sessões anteriores',async()=>{const f=await fixture();const c=await f.login();await f.call('/auth/recover',{email:'a@example.invalid'});const t=new URL(f.mails[0].url).searchParams.get('token');assert.ok(t);assert.equal((await f.call('/auth/activate',{token:t,password:'New-synthetic-password!'})).r.status,200);assert.equal((await f.call('/dashboard',null,c)).r.status,401);assert.equal((await f.call('/auth/activate',{token:t,password:'New-synthetic-password!'})).r.status,400);assert.ok(!JSON.stringify(f.store.state).includes(t));});
test('anexos rejeitam formato disfarçado e tamanho excessivo',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/requests',{subject:'Arquivo',description:'Teste'},c)).data.request.id;assert.equal((await f.call('/files',{requestId:id,name:'x.png',type:'image/png',data:Buffer.from('<script>bad</script>').toString('base64')},c)).r.status,400);assert.equal((await f.call('/files',{requestId:id,name:'x.txt',type:'text/plain',data:Buffer.alloc(2097153).toString('base64')},c)).r.status,400);});
test('comunicados respeitam destinatário e confirmação de leitura',async()=>{const f=await fixture();const a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');await f.call('/admin/notices',{userId:'a',title:'Privado',text:'Para A'},o);const id=f.store.state.notices[0].id;assert.equal((await f.call('/dashboard',null,b)).data.notices.length,0);assert.equal((await f.call('/notices/read',{id},b)).r.status,400);await f.call('/notices/read',{id},a);await f.call('/notices/read',{id},a);assert.equal(f.store.state.notices[0].readBy.length,1);});
test('mutações concorrentes não perdem solicitações',async()=>{const f=await fixture();const c=await f.login();await Promise.all(Array.from({length:15},(_,i)=>f.call('/requests',{subject:`Solicitação ${i}`,description:'Teste concorrente'},c)));assert.equal(f.store.state.requests.length,15);});
test('proprietário só é ativado pelo e-mail configurado e pelo token recebido',async()=>{const f=await fixture();f.env.OWNER_EMAIL='a@example.invalid';await f.call('/auth/recover',{email:'a@example.invalid'});assert.equal(f.store.state.users.find(u=>u.id==='a').role,'client');const t=new URL(f.mails[0].url).searchParams.get('token');await f.call('/auth/activate',{token:t,password:'Synthetic-owner-password!'});assert.equal(f.store.state.users.find(u=>u.id==='a').role,'owner');assert.equal(f.store.state.users.find(u=>u.id==='b').role,'client');});
test('reconciliação rejeita pagamento de outro pedido',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;f.payments.set('123',{id:123,external_reference:'another-order',collector_id:123,currency_id:'BRL',live_mode:true,date_last_updated:new Date().toISOString()});assert.equal((await f.call(`/orders/${id}/reconcile`,{paymentId:'123'},c)).r.status,400);assert.equal(f.store.state.orders[0].paid,0);});
test('configuração inicial exige segredo válido, prazo e ausência de proprietário ativo',async()=>{const f=await fixture();f.store.state.users=f.store.state.users.filter(u=>u.role!=='owner');f.env.OWNER_EMAIL='owner@example.invalid';f.env.OWNER_SETUP_HASH=digest('synthetic-bootstrap-token');f.env.OWNER_SETUP_EXPIRES=new Date(Date.now()+60000).toISOString();const body={token:'synthetic-bootstrap-token',name:'Responsável fictício',password:'Synthetic-owner-setup!'};assert.equal((await f.call('/auth/bootstrap',{...body,token:'wrong'})).r.status,403);assert.equal((await f.call('/auth/bootstrap',body)).r.status,200);assert.equal((await f.call('/auth/bootstrap',body)).r.status,403);});
test('convites individuais operam sem e-mail e recuperação administrativa respeita permissões',async()=>{const f=await fixture();delete f.env.RESEND_API_KEY;const o=await f.login('owner@example.invalid');const r=await f.call('/admin/invite',{name:'Novo cliente fictício',email:'new@example.invalid',role:'client'},o);assert.equal(r.r.status,200);const t=new URL(r.data.activationUrl).searchParams.get('token');assert.equal((await f.call('/auth/activate',{token:t,password:'Synthetic-invite-password!'})).r.status,200);const c=await f.login();assert.equal((await f.call('/admin/recovery',{id:'b'},c)).r.status,403);assert.equal((await f.call('/admin/recovery',{id:'b'},o)).r.status,200);});

test('checkout identifica MINDMORPHIA sem alterar referência da conciliação',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,200);const p=f.preferences[0];assert.equal(p.external_reference,id);assert.equal(p.statement_descriptor,'MINDMORPHIA');assert.equal(p.metadata.brand,'MINDMORPHIA');assert.equal(p.metadata.order_id,id);assert.equal(p.metadata.payment_attempt_id,f.store.state.orders[0].payments[0].id);assert.match(p.additional_info,/MINDMORPHIA/);assert.equal(p.items[0].unit_price,498.5);assert.equal(p.payment_methods.installments,3);});

test('recebedor vem da conta autenticada e checkout alheio não é liberado',async()=>{const f=await fixture();delete f.env.MERCADOPAGO_COLLECTOR_ID;const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;f.payments.set('preferenceCollector',999);assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,400);assert.equal(f.store.state.orders[0].payments[0].state,'failed');f.payments.set('preferenceCollector',123);assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,200);f.payments.set('account',{id:123,tags:['test_user']});assert.equal((await f.call(`/orders/${id}/reconcile`,{paymentId:'123'},c)).r.status,503);});
test('proprietário ativo recebe recuperação de senha com assunto correto',async()=>{const f=await fixture();f.env.OWNER_EMAIL='owner@example.invalid';await f.call('/auth/recover',{email:'owner@example.invalid'});assert.equal(f.mails[0].label,'Recuperar acesso');assert.equal(f.store.state.tokens[0].purpose,'reset');});
