import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createApp} from '../lib/app.mjs';
import {MemoryStore} from '../lib/storage.mjs';
import {hashPassword,digest} from '../lib/security.mjs';
import {quote,termsVersion} from '../lib/catalog.mjs';
const origin='https://mindmorphia-site.vercel.app';
async function fixture(){const store=new MemoryStore();const hash=await hashPassword('Synthetic-testing-2026!');store.state.users=[{id:'a',name:'Cliente A',email:'a@example.invalid',role:'client',password:hash,active:true},{id:'b',name:'Cliente B',email:'b@example.invalid',role:'client',password:hash,active:true},{id:'owner',name:'Responsável',email:'owner@example.invalid',role:'owner',password:hash,active:true},{id:'staff',name:'Equipe restrita',email:'staff@example.invalid',role:'staff',permissions:['requests'],password:hash,active:true}];const env={SITE_URL:origin,BLOB_READ_WRITE_TOKEN:'synthetic',RESEND_API_KEY:'synthetic',EMAIL_FROM:'teste@example.invalid',MERCADOPAGO_ACCESS_TOKEN:'synthetic',MERCADOPAGO_WEBHOOK_SECRET:'synthetic-secret',MERCADOPAGO_COLLECTOR_ID:'123'};const mails=[];const notifications=[];const payments=new Map();const preferences=[];const app=createApp({store,env,notifier:async(_e,n)=>{notifications.push(n);return {id:'notification-'+notifications.length};},mailer:async(_e,to,url,label)=>{mails.push({to,url,label});return {id:'synthetic'};},payment:async(_e,path,body)=>{if(path==='/users/me')return payments.get('account')||{id:123,tags:[]};if(body){preferences.push(body);return {id:'preference',collector_id:payments.get('preferenceCollector')||123,init_point:'https://www.mercadopago.com.br/checkout/v1/redirect?pref_id=synthetic'};}return payments.get(path.split('/').pop());}});async function call(path,body,cookie='',extra={}){const r=await app(new Request(origin+'/api'+path,{method:body?'POST':'GET',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})}));let data;try{data=await r.clone().json();}catch{data=await r.clone().text();}return {r,data};}async function login(email='a@example.invalid'){const {r}=await call('/auth/login',{email,password:'Synthetic-testing-2026!'});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}return {store,env,mails,payments,preferences,notifications,call,login};}
const orderBody={items:[{id:'impacto',quantity:1}],mode:'deposit',brief:'Projeto de teste sintético',accepted:true,termsVersion,key:'synthetic-request-0001'};
test('preço do servidor, entrada de 50%, cupons e catálogo inválido',async()=>{const f=await fixture();f.store.state.coupons.push({code:'MM10',percent:10,active:true});const q=quote(f.store.state,{...orderBody,coupon:'MM10',total:1});assert.equal(q.total,89730);assert.equal(q.due,44865);assert.equal(q.shipping,0);assert.throws(()=>quote(f.store.state,{items:[{id:'unknown',quantity:1}]}));assert.throws(()=>quote(f.store.state,{items:[{id:'impacto',quantity:0}]}));assert.throws(()=>quote(f.store.state,{...orderBody,coupon:'INVALID'}));});
test('cookie seguro, CSRF e logout revogam consultas',async()=>{const f=await fixture();const c=await f.login();const r=await f.call('/auth/login',{email:'a@example.invalid',password:'Synthetic-testing-2026!'});assert.match(r.r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.match(r.r.headers.get('set-cookie'),/Secure/);assert.equal((await f.call('/requests',{subject:'Teste',description:'Teste'},c,{origin:'https://attacker.invalid'})).r.status,403);await f.call('/auth/logout',{},c);assert.equal((await f.call('/dashboard',null,c)).r.status,401);});
test('clientes não leem projetos, solicitações, notas internas ou arquivos alheios',async()=>{const f=await fixture();const a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');const result=await f.call('/requests',{subject:'Cliente A',description:'Descrição'},a);const id=result.data.request.id;await f.call(`/requests/${id}/message`,{text:'Nota privada',internal:true},o);assert.equal((await f.call(`/requests/${id}/message`,{text:'Invasão'},b)).r.status,404);assert.equal((await f.call('/dashboard',null,b)).data.requests.length,0);assert.equal((await f.call('/dashboard',null,a)).data.requests[0].messages.length,0);const file=await f.call('/files',{requestId:id,name:'teste.txt',type:'text/plain',data:Buffer.from('Sintético').toString('base64')},a);assert.equal(file.r.status,201);assert.equal((await f.call(`/files/${file.data.id}`,null,b)).r.status,404);assert.equal((await f.call(`/files/${file.data.id}`,null,a)).r.status,200);assert.equal((await f.call(`/files/${file.data.id}`)).r.status,401);});
test('permissões limitam equipe e suspensão invalida próxima operação',async()=>{const f=await fixture();const s=await f.login('staff@example.invalid'),o=await f.login('owner@example.invalid');assert.equal((await f.call('/admin/catalog',{name:'X',price:100},s)).r.status,403);assert.equal((await f.call('/admin/team',{id:'staff',permissions:['catalog']},s)).r.status,403);assert.equal((await f.call('/dashboard',null,s)).data.clients.length,0);await f.call('/admin/team',{id:'staff',permissions:[],suspended:true},o);assert.equal((await f.call('/dashboard',null,s)).r.status,401);});
test('orçamento exige titular, versão atual e decisão única registrada',async()=>{const f=await fixture();const a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');const id=(await f.call('/requests',{subject:'Serviço',description:'Ampliação'},a)).data.request.id;await f.call(`/requests/${id}/proposal`,{scope:'Nova página',amount:20000,dueDate:'2026-10-20'},o);const proposalId=(await f.call('/dashboard',null,a)).data.requests[0].proposal.id;assert.equal((await f.call(`/requests/${id}/decision`,{proposalId,decision:'accepted'},b)).r.status,404);assert.equal((await f.call(`/requests/${id}/decision`,{proposalId:'old',decision:'accepted'},a)).r.status,400);assert.equal((await f.call(`/requests/${id}/decision`,{proposalId,decision:'accepted'},a)).r.status,200);assert.equal((await f.call(`/requests/${id}/decision`,{proposalId,decision:'rejected'},a)).r.status,400);});
test('pedido idempotente preserva preço e condições após edição',async()=>{const f=await fixture();const c=await f.login();const first=await f.call('/orders',orderBody,c);const second=await f.call('/orders',{...orderBody,total:1},c);assert.equal(first.data.order.id,second.data.order.id);assert.equal(first.data.order.total,99700);assert.equal(f.store.state.orders.length,1);const owner=await f.login('owner@example.invalid');await f.call('/admin/catalog',{id:'impacto',name:'Impacto',scope:'Novo escopo',price:120000,active:true},owner);assert.equal(f.store.state.orders[0].total,99700);assert.equal((await f.call('/quote',orderBody,c)).data.total,120000);});
test('pagamento valida assinatura, conta, moeda, valor e modo real',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;await f.call(`/orders/${id}/payment`,{},c);assert.equal((await f.call('/webhooks/mercadopago?data.id=123',{},'',{'x-request-id':'rid','x-signature':'ts=1,v1=bad'})).r.status,401);const signature=createHmac('sha256',f.env.MERCADOPAGO_WEBHOOK_SECRET).update('id:123;request-id:rid;ts:1;').digest('hex');const headers={'x-request-id':'rid','x-signature':`ts=1,v1=${signature}`};const p={id:123,collector_id:123,currency_id:'BRL',live_mode:true,external_reference:id,status:'approved',transaction_amount:498.5,date_last_updated:'2026-10-09T01:00:00Z'};f.payments.set('123',{...p,collector_id:999});assert.equal((await f.call('/webhooks/mercadopago?data.id=123',{},'',headers)).r.status,400);f.payments.set('123',p);assert.equal((await f.call('/webhooks/mercadopago?data.id=123',{},'',headers)).r.status,200);assert.equal(f.store.state.orders[0].paid,49850);assert.equal(f.store.state.orders[0].balance,49850);assert.equal(f.store.state.projects.length,1);await f.call('/webhooks/mercadopago?data.id=123',{},'',headers);assert.equal(f.store.state.projects.length,1);assert.equal(f.store.state.orders[0].paid,49850);});
test('cancelamento persiste e pagamento tardio exige análise sem entrega automática',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;await f.call(`/orders/${id}/payment`,{},c);await f.call(`/orders/${id}/cancel`,{},c);assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,400);f.payments.set('123',{id:123,collector_id:123,currency_id:'BRL',live_mode:true,external_reference:id,status:'approved',transaction_amount:498.5,date_last_updated:'2026-10-09T01:00:00Z'});const signature=createHmac('sha256',f.env.MERCADOPAGO_WEBHOOK_SECRET).update('id:123;request-id:rid;ts:1;').digest('hex');await f.call('/webhooks/mercadopago?data.id=123',{},'',{'x-request-id':'rid','x-signature':`ts=1,v1=${signature}`});assert.equal(f.store.state.orders[0].status,'cancelamento_em_analise');assert.equal(f.store.state.projects.length,0);});
test('recuperação tem token de uso único e revoga sessões anteriores',async()=>{const f=await fixture();const c=await f.login();await f.call('/auth/recover',{email:'a@example.invalid'});const t=new URL(f.mails[0].url).searchParams.get('token');assert.ok(t);assert.equal((await f.call('/auth/activate',{token:t,password:'New-synthetic-password!'})).r.status,200);assert.equal((await f.call('/dashboard',null,c)).r.status,401);assert.equal((await f.call('/auth/activate',{token:t,password:'New-synthetic-password!'})).r.status,400);assert.ok(!JSON.stringify(f.store.state).includes(t));});
test('anexos rejeitam formato disfarçado e tamanho excessivo',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/requests',{subject:'Arquivo',description:'Teste'},c)).data.request.id;assert.equal((await f.call('/files',{requestId:id,name:'x.png',type:'image/png',data:Buffer.from('<script>bad</script>').toString('base64')},c)).r.status,400);assert.equal((await f.call('/files',{requestId:id,name:'x.txt',type:'text/plain',data:Buffer.alloc(2097153).toString('base64')},c)).r.status,400);});
test('comunicados respeitam destinatário e confirmação de leitura',async()=>{const f=await fixture();const a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');await f.call('/admin/notices',{userId:'a',title:'Privado',text:'Para A'},o);const id=f.store.state.notices[0].id;assert.equal((await f.call('/dashboard',null,b)).data.notices.length,0);assert.equal((await f.call('/notices/read',{id},b)).r.status,400);await f.call('/notices/read',{id},a);await f.call('/notices/read',{id},a);assert.equal(f.store.state.notices[0].readBy.length,1);});
test('mutações concorrentes não perdem solicitações',async()=>{const f=await fixture();const c=await f.login();await Promise.all(Array.from({length:15},(_,i)=>f.call('/requests',{subject:`Solicitação ${i}`,description:'Teste concorrente'},c)));assert.equal(f.store.state.requests.length,15);});
test('proprietário só é ativado pelo e-mail configurado e pelo token recebido',async()=>{const f=await fixture();f.env.OWNER_EMAIL='a@example.invalid';await f.call('/auth/recover',{email:'a@example.invalid'});assert.equal(f.store.state.users.find(u=>u.id==='a').role,'client');const t=new URL(f.mails[0].url).searchParams.get('token');await f.call('/auth/activate',{token:t,password:'Synthetic-owner-password!'});assert.equal(f.store.state.users.find(u=>u.id==='a').role,'owner');assert.equal(f.store.state.users.find(u=>u.id==='b').role,'client');});
test('reconciliação rejeita pagamento de outro pedido',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;f.payments.set('123',{id:123,external_reference:'another-order',collector_id:123,currency_id:'BRL',live_mode:true,date_last_updated:new Date().toISOString()});assert.equal((await f.call(`/orders/${id}/reconcile`,{paymentId:'123'},c)).r.status,400);assert.equal(f.store.state.orders[0].paid,0);});
test('configuração inicial exige segredo válido, prazo e ausência de proprietário ativo',async()=>{const f=await fixture();f.store.state.users=f.store.state.users.filter(u=>u.role!=='owner');f.env.OWNER_EMAIL='owner@example.invalid';f.env.OWNER_SETUP_HASH=digest('synthetic-bootstrap-token');f.env.OWNER_SETUP_EXPIRES=new Date(Date.now()+60000).toISOString();const body={token:'synthetic-bootstrap-token',name:'Responsável fictício',password:'Synthetic-owner-setup!'};assert.equal((await f.call('/auth/bootstrap',{...body,token:'wrong'})).r.status,403);assert.equal((await f.call('/auth/bootstrap',body)).r.status,200);assert.equal((await f.call('/auth/bootstrap',body)).r.status,403);});
test('convites individuais operam sem e-mail e recuperação administrativa respeita permissões',async()=>{const f=await fixture();delete f.env.RESEND_API_KEY;const o=await f.login('owner@example.invalid');const r=await f.call('/admin/invite',{name:'Novo cliente fictício',email:'new@example.invalid',role:'client'},o);assert.equal(r.r.status,200);const t=new URL(r.data.activationUrl).searchParams.get('token');assert.equal((await f.call('/auth/activate',{token:t,password:'Synthetic-invite-password!'})).r.status,200);const c=await f.login();assert.equal((await f.call('/admin/recovery',{id:'b'},c)).r.status,403);assert.equal((await f.call('/admin/recovery',{id:'b'},o)).r.status,200);});

test('checkout identifica MINDMORPHIA sem alterar referência da conciliação',async()=>{const f=await fixture();const c=await f.login();const id=(await f.call('/orders',orderBody,c)).data.order.id;assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,200);const p=f.preferences[0];assert.equal(p.external_reference,id);assert.equal(p.statement_descriptor,'MINDMORPHIA');assert.equal(p.metadata.brand,'MINDMORPHIA');assert.equal(p.metadata.order_id,id);assert.equal(p.metadata.payment_attempt_id,f.store.state.orders[0].payments[0].id);assert.match(p.additional_info,/MINDMORPHIA/);assert.equal(p.items[0].unit_price,498.5);assert.equal(p.payment_methods.installments,3);});

test('recebedor vem da conta autenticada e checkout alheio não é liberado',async()=>{const f=await fixture();delete f.env.MERCADOPAGO_COLLECTOR_ID;const c=await f.login();assert.equal((await f.call('/admin/payment-account',null,c)).r.status,403);const owner=await f.login('owner@example.invalid');assert.deepEqual((await f.call('/admin/payment-account',null,owner)).data,{ok:true,collectorId:'123'});const id=(await f.call('/orders',orderBody,c)).data.order.id;f.payments.set('preferenceCollector',999);assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,400);assert.equal(f.store.state.orders[0].payments[0].state,'failed');f.payments.set('preferenceCollector',123);assert.equal((await f.call(`/orders/${id}/payment`,{},c)).r.status,200);f.payments.set('account',{id:123,tags:['test_user']});assert.equal((await f.call(`/orders/${id}/reconcile`,{paymentId:'123'},c)).r.status,503);});
test('proprietário ativo recebe recuperação de senha com assunto correto',async()=>{const f=await fixture();f.env.OWNER_EMAIL='owner@example.invalid';await f.call('/auth/recover',{email:'owner@example.invalid'});assert.equal(f.mails[0].label,'Recuperar acesso');assert.equal(f.store.state.tokens[0].purpose,'reset');});

test('acessos e mídia têm preço real de catálogo e não aceitam entrada parcial',async()=>{const f=await fixture();for(const [id,total] of [['canva-pro-12',9990],['canva-pro-24',12990],['google-ai-pro-18',24990],['midia-avulsa-4990',4990],['midia-avulsa-9990',9990]]){const input={items:[{id,quantity:1}],mode:'full'};assert.equal(quote(f.store.state,input).total,total);assert.throws(()=>quote(f.store.state,{...input,mode:'deposit'}));}assert.throws(()=>quote(f.store.state,{items:[{id:'canva-pro-12',quantity:2}],mode:'full'}));assert.throws(()=>quote(f.store.state,{items:[{id:'canva-pro-12',quantity:1},{id:'canva-pro-24',quantity:1}],mode:'full'}));const c=await f.login();const body={...orderBody,items:[{id:'midia-avulsa-4990',quantity:1}],mode:'full'};assert.equal((await f.call('/orders',body,c)).r.status,400);const r=await f.call('/orders',{...body,mediaAgreed:true},c);assert.equal(r.r.status,201);assert.match(r.data.order.mediaAgreement.deadline,/5 dias úteis/);assert.match(r.data.order.items[0].scope,/Mind Marketing/);});

async function approveOrder(f,id,amount){f.payments.set('123',{id:123,collector_id:123,currency_id:'BRL',live_mode:true,external_reference:id,status:'approved',transaction_amount:amount/100,date_last_updated:'2026-10-09T01:00:00Z'});const signature=createHmac('sha256',f.env.MERCADOPAGO_WEBHOOK_SECRET).update('id:123;request-id:rid;ts:1;').digest('hex');return f.call('/webhooks/mercadopago?data.id=123',{},'',{'x-request-id':'rid','x-signature':`ts=1,v1=${signature}`});}
test('compra digital envia confirmação única e link privado somente após quitação',async()=>{const f=await fixture(),a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');const result=await f.call('/orders',{...orderBody,items:[{id:'canva-pro-12',quantity:1}],mode:'full',activationEmail:'conta@example.invalid'},a);const id=result.data.order.id;await f.call(`/orders/${id}/payment`,{},a);assert.equal((await approveOrder(f,id,9990)).r.status,200);const project=f.store.state.projects[0];assert.equal(project.status,'Ativação pendente');assert.equal(project.activationContactDueAt,'2026-10-10T01:00:00.000Z');assert.equal(f.notifications.length,1);assert.match(f.notifications[0].subject,/Pagamento confirmado/);assert.match(f.notifications[0].text,/24 horas/);await approveOrder(f,id,9990);assert.equal(f.notifications.length,1);const body={productId:'canva-pro-12',url:'https://www.canva.com/brand/join?token=synthetic-link',instructions:'Abra o link na sua própria conta.'};assert.equal((await f.call(`/projects/${project.id}/deliver-access`,body,a)).r.status,403);assert.equal((await f.call(`/projects/${project.id}/deliver-access`,{...body,url:'javascript:alert(1)'},o)).r.status,400);assert.equal((await f.call(`/projects/${project.id}/deliver-access`,body,o)).r.status,200);assert.equal(f.notifications.length,2);assert.match(f.notifications[1].text,/conta@example.invalid/);assert.equal((await f.call('/dashboard',null,b)).data.projects.length,0);const own=(await f.call('/dashboard',null,a)).data.projects[0];assert.equal(own.accesses[0].url,body.url);assert.equal(own.status,'Link de acesso enviado');assert.ok(own.activationLinksSentAt);assert.equal((await f.call(`/projects/${project.id}/deliver-access`,body,o)).r.status,400);assert.equal(f.notifications.length,2);await f.call(`/orders/${id}/cancel`,{},a);assert.equal((await f.call(`/projects/${project.id}/deliver-access`,{...body,productId:'google-ai-pro-18'},o)).r.status,400);});
test('migração do catálogo conserva edições e não duplica novos serviços',async()=>{const f=await fixture();f.store.state.catalog=f.store.state.catalog.filter(p=>p.category==='Websites');f.store.state.catalog[0].price=100000;const r=await f.call('/catalog');assert.equal(r.data.products.length,8);assert.equal(r.data.products[0].price,100000);await f.call('/catalog');assert.equal(f.store.state.catalog.length,8);const o=await f.login('owner@example.invalid');await f.call('/admin/catalog',{id:'canva-pro-12',name:'Canva Pro atualizado',price:11000,active:true},o);assert.equal(f.store.state.catalog.find(p=>p.id==='canva-pro-12').kind,'digital_access');assert.ok(f.store.state.catalog.find(p=>p.id==='canva-pro-12').image);});


test('contato público é persistido uma vez, notificado e isolado por permissão',async()=>{
 const f=await fixture();f.env.OWNER_EMAIL='owner@example.invalid';
 const body={name:'Contato fictício',email:'lead@example.invalid',phone:'',type:'Uma pergunta',message:'Teste sintético do contato.',key:'synthetic-contact-key-0001'};
 const first=await f.call('/contact',body);assert.equal(first.r.status,201);assert.match(first.data.reference,/^[a-f0-9]{8}$/);
 assert.equal((await f.call('/contact',body)).data.reference,first.data.reference);assert.equal(f.store.state.contacts.length,1);assert.equal(f.notifications.length,1);assert.equal(f.store.state.users.length,4);
 const c=await f.login(),staff=await f.login('staff@example.invalid'),owner=await f.login('owner@example.invalid');
 assert.deepEqual((await f.call('/dashboard',null,c)).data.contacts,[]);
 const contacts=(await f.call('/dashboard',null,staff)).data.contacts;assert.equal(contacts.length,1);assert.ok(!contacts[0].key);
 const id=contacts[0].id;assert.equal((await f.call(`/admin/contacts/${id}`,{status:'Concluído',notes:'Privado'},c)).r.status,403);
 assert.equal((await f.call(`/admin/contacts/${id}`,{status:'Em atendimento',notes:'Acompanhamento de teste'},staff)).r.status,200);
 assert.equal((await f.call('/dashboard',null,owner)).data.contacts[0].status,'Em atendimento');
});
test('contato rejeita origem, tamanho e spam sem criar contas ou cobrar',async()=>{
 const f=await fixture(),body={name:'QA',email:'qa@example.invalid',phone:'',type:'Uma pergunta',message:'Teste',key:'synthetic-contact-key-0001'};
 assert.equal((await f.call('/contact',body,'',{origin:'https://attacker.invalid'})).r.status,403);
 assert.equal((await f.call('/contact',{...body,message:'x'.repeat(1001)})).r.status,400);
 assert.equal((await f.call('/contact',{...body,email:'invalid'})).r.status,400);
 assert.equal((await f.call('/contact',{...body,website:'bot'})).r.status,202);assert.equal(f.store.state.contacts?.length||0,0);
 for(let i=0;i<5;i++)assert.equal((await f.call('/contact',{...body,key:'synthetic-contact-key-'+i})).r.status,201);
 assert.equal((await f.call('/contact',{...body,key:'synthetic-contact-key-limit'})).r.status,429);
 assert.equal(f.store.state.orders.length,0);
});
test('erros internos não divulgam detalhes do armazenamento',async()=>{
 const store=new MemoryStore();store.read=async()=>{throw new Error('synthetic-private-storage-detail');};
 const app=createApp({store});const r=await app(new Request(origin+'/api/catalog'));assert.equal(r.status,500);assert.ok(!(await r.text()).includes('synthetic-private-storage-detail'));
});
test('identificadores administrativos não aceitam injeção em atributos da interface',async()=>{
 const f=await fixture(),o=await f.login('owner@example.invalid');
 assert.equal((await f.call('/admin/catalog',{id:'x" autofocus onfocus="bad',name:'Teste',price:100,active:true},o)).r.status,400);
 assert.equal((await f.call('/admin/projects',{id:'x" autofocus onfocus="bad',userId:'a',name:'Teste'},o)).r.status,400);
});
test('assinatura sem observações é contratável e trabalhos continuam exigindo descrição',async()=>{
 const f=await fixture(),c=await f.login();
 const digital={...orderBody,items:[{id:'canva-pro-12',quantity:1}],mode:'full',brief:''};
 const r=await f.call('/orders',digital,c);assert.equal(r.r.status,201);assert.equal(r.data.order.brief,'Sem observações adicionais.');
 assert.equal((await f.call('/orders',{...orderBody,key:'synthetic-website-brief-key',brief:''},c)).r.status,400);
 assert.equal((await f.call('/quote',{items:[null]},c)).r.status,400);
});

test('equipe de projetos pode atualizar projeto sem acesso ao cadastro geral e titular não muda',async()=>{
 const f=await fixture();f.store.state.users.find(u=>u.id==='staff').permissions=['projects'];
 const o=await f.login('owner@example.invalid'),staff=await f.login('staff@example.invalid'),id=crypto.randomUUID();
 assert.equal((await f.call('/admin/projects',{id,userId:'a',name:'Projeto QA',scope:'Teste'},o)).r.status,200);
 assert.equal((await f.call('/dashboard',null,staff)).data.clients.length,0);
 assert.equal((await f.call('/admin/projects',{id,userId:'a',name:'Projeto atualizado',scope:'Teste'},staff)).r.status,200);
 assert.equal((await f.call('/admin/projects',{id,userId:'b',name:'Troca indevida',scope:'Teste'},staff)).r.status,400);
});

test('resumo preserva preço contratado e exige titular ou permissão de pedidos',async()=>{
 const f=await fixture(),a=await f.login(),b=await f.login('b@example.invalid'),o=await f.login('owner@example.invalid');const id=(await f.call('/orders',orderBody,a)).data.order.id;
 assert.equal((await f.call(`/orders/${id}/summary`,null,b)).r.status,404);assert.equal((await f.call(`/orders/${id}/summary`)).r.status,401);
 await f.call('/admin/catalog',{id:'impacto',name:'Impacto',price:120000,active:true},o);
 const r=await f.call(`/orders/${id}/summary`,null,a);assert.equal(r.r.status,200);assert.match(r.r.headers.get('content-disposition'),/attachment/);assert.match(r.data,/997,00/);assert.ok(!r.data.includes('1.200,00'));assert.equal(r.r.headers.get('cache-control'),'no-store');
});

test('oferta alterada exige revisão e tentativa já registrada preserva contrato original',async()=>{
 const f=await fixture(),a=await f.login(),o=await f.login('owner@example.invalid');
 const q=(await f.call('/quote',orderBody,a)).data;
 await f.call('/admin/catalog',{id:'impacto',name:'Impacto',price:120000,scope:'Escopo alterado',active:true},o);
 assert.equal((await f.call('/orders',{...orderBody,quoteFingerprint:q.fingerprint},a)).r.status,400);assert.equal(f.store.state.orders.length,0);
 const updated=(await f.call('/quote',orderBody,a)).data;const body={...orderBody,quoteFingerprint:updated.fingerprint};
 const first=(await f.call('/orders',body,a)).data.order;
 await f.call('/admin/catalog',{id:'impacto',name:'Impacto',price:130000,scope:'Novo escopo',active:false},o);
 const retry=(await f.call('/orders',body,a)).data.order;assert.equal(retry.id,first.id);assert.equal(retry.total,120000);assert.equal(f.store.state.orders.length,1);
});
