import {randomUUID} from 'node:crypto';
import {quote,termsVersion} from './catalog.mjs';
import {token,digest,hashPassword,checkPassword,verifyWebhook,can,permissions} from './security.mjs';
import {serviceConfig,sendAccessEmail,mpRequest,checkoutUrl} from './services.mjs';
const now=()=>new Date().toISOString();
const safeUser=u=>({id:u.id,name:u.name,email:u.email,phone:u.phone||'',role:u.role,active:u.active,suspended:!!u.suspended,permissions:u.permissions||[]});
const text=(v,max=4000)=>typeof v==='string'?v.trim().slice(0,max):'';
const email=v=>text(v,254).toLowerCase();
function requireValue(v,message){if(!v)throw Object.assign(new Error(message),{status:400});return v;}
function fail(status,message){throw Object.assign(new Error(message),{status});}
function audit(s,actor,action,id){s.audit.push({id:randomUUID(),actor:actor?.id||'system',action,target:id,at:now()});}
function visibleRequest(r,user){return {...r,messages:r.messages.filter(m=>!m.internal||user.role!=='client')};}
const cookie=(value,secure)=>`mm_session=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${value?28800:0}${secure?'; Secure':''}`;
export function createApp({store,env={},mailer=sendAccessEmail,payment=mpRequest}){
 const config=()=>serviceConfig(env);
 const origin=env.SITE_URL||'https://mindmorphia-site.vercel.app';
 async function session(req,s){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)mm_session=([a-f0-9]{64})/)?.[1];const sess=raw&&s.sessions.find(x=>x.hash===digest(raw)&&Date.parse(x.expiresAt)>Date.now());return sess?s.users.find(u=>u.id===sess.userId&&u.active&&!u.suspended):null;}
 function own(record,user,permission){if(!record||!(record.userId===user.id||can(user,permission)))fail(404,'Registro não encontrado.');return record;}
 async function rate(req,key,max=20){const ip=req.headers.get('x-vercel-forwarded-for')||req.headers.get('x-forwarded-for')||'local';const id=digest(`${ip.split(',')[0]}:${key}`);await store.change(s=>{s.limits=s.limits.filter(r=>r.until>Date.now());let r=s.limits.find(r=>r.id===id);if(!r){r={id,count:0,until:Date.now()+15*60*1000};s.limits.push(r);}if(++r.count>max)fail(429,'Muitas tentativas. Aguarde alguns minutos.');});}
 async function accessToken(userId,purpose,address){const raw=token();const hash=digest(raw);await store.change(s=>{s.tokens=s.tokens.filter(t=>Date.parse(t.expiresAt)>Date.now());s.tokens.push({hash,userId,purpose,expiresAt:new Date(Date.now()+3600000).toISOString()});});try{await mailer(env,address,`${origin}/acesso?token=${raw}`,purpose==='reset'?'Recuperar acesso':'Ativar acesso');}catch(e){await store.change(s=>{s.tokens=s.tokens.filter(t=>t.hash!==hash);});throw e;}}
 async function paymentCollector(){if(env.MERCADOPAGO_COLLECTOR_ID)return env.MERCADOPAGO_COLLECTOR_ID;const account=await payment(env,'/users/me');if(!Number.isSafeInteger(account?.id)||account.id<=0||(account.tags||[]).includes('test_user'))fail(503,'Conta produtiva do pagamento não confirmada.');return String(account.id);}
 async function syncPayment(id,expectedOrderId){const collector=await paymentCollector();const p=await payment(env,`/v1/payments/${encodeURIComponent(id)}`);if(expectedOrderId&&p.external_reference!==expectedOrderId)fail(400,'Pagamento não corresponde ao pedido.');if(String(p.collector_id)!==collector||p.currency_id!=='BRL'||p.live_mode!==true||!p.external_reference||!Number.isFinite(Date.parse(p.date_last_updated)))fail(400,'Pagamento não corresponde à operação.');await store.change(s=>{const o=s.orders.find(o=>o.id===p.external_reference);if(!o)fail(404,'Pedido não encontrado.');const entry=o.payments.find(x=>x.paymentId===String(p.id));const open=o.payments.find(x=>x.state==='pending'&&x.amount===Math.round(p.transaction_amount*100));const attempt=entry||open;if(!attempt||attempt.amount!==Math.round(p.transaction_amount*100))fail(400,'Valor não corresponde ao pedido.');if(entry&&Date.parse(entry.updatedAt)>=Date.parse(p.date_last_updated))return;if(o.payments.some(x=>x!==attempt&&x.paymentId===String(p.id)))return;attempt.paymentId=String(p.id);attempt.state=p.status;attempt.updatedAt=p.date_last_updated;attempt.refunded=Math.round(Number(p.transaction_amount_refunded||0)*100);if(!Number.isSafeInteger(attempt.refunded)||attempt.refunded<0||attempt.refunded>attempt.amount)fail(400,'Estorno inválido.');const paid=o.payments.filter(x=>x.state==='approved').reduce((n,x)=>n+x.amount-x.refunded,0);o.paid=paid;o.balance=Math.max(0,o.total-paid);o.status=o.cancellationAt?(paid?'cancelamento_em_analise':'cancelado'):paid>=o.total?'pago':paid?'entrada_paga':'aguardando_pagamento';if(p.status==='refunded'||p.status==='charged_back')o.status=p.status==='refunded'?'estornado':'contestacao';if(!o.cancellationAt&&paid>0){let project=s.projects.find(x=>x.orderId===o.id);if(!project){project={id:randomUUID(),orderId:o.id,userId:o.userId,name:o.items.map(i=>i.name).join(' + '),scope:o.items.map(i=>i.scope).join('\n'),status:'Materiais pendentes',dueDate:'',stages:[],history:[],createdAt:now()};s.projects.push(project);}project.history.push({at:now(),text:'Pagamento conciliado pelo provedor.'});}audit(s,null,'payment.sync',o.id);});}
 return async function handle(req){const url=new URL(req.url);const path=url.pathname.replace(/^\/api/,'').replace(/\/$/,'')||'/';const secure=url.protocol==='https:';const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};const response=(value,status=200,extra={})=>new Response(JSON.stringify(value),{status,headers:{...headers,...extra}});
 try{
 if(req.method!=='GET'&&!['/webhooks/mercadopago'].includes(path)&&req.headers.get('origin')!==url.origin)fail(403,'Origem inválida.');
 if(path==='/catalog'&&req.method==='GET'){const s=await store.read();return response({products:s.catalog.filter(x=>x.active),services:{payment:config().payment,email:config().email},termsVersion});}
 if(path==='/status'&&req.method==='GET')return response({ok:true,version:'1.0.0',payment:config().payment,email:config().email,storage:config().storage});
 if(req.method==='POST'&&path==='/webhooks/mercadopago'){if(!config().payment)fail(503,'Pagamento não configurado.');const id=verifyWebhook(req.url,req.headers,env.MERCADOPAGO_WEBHOOK_SECRET);if(!id)fail(401,'Assinatura inválida.');await syncPayment(id);return response({ok:true});}
 const length=Number(req.headers.get('content-length')||0);if(length>3000000)fail(413,'Arquivo ou mensagem muito grande.');
 let body={};if(req.method!=='GET'){const raw=await req.text();if(Buffer.byteLength(raw)>3000000)fail(413,'Arquivo ou mensagem muito grande.');try{body=raw?JSON.parse(raw):{};}catch{fail(400,'Dados inválidos.');}}
 if(path==='/auth/register'&&req.method==='POST'){await rate(req,'register',8);if(!config().email)fail(503,'Cadastro por e-mail ainda não ativado. Entre em contato para solicitar acesso.');const address=email(body.email);requireValue(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address),'E-mail inválido.');const name=requireValue(text(body.name,100),'Informe seu nome.');const hash=await hashPassword(body.password);let id;await store.change(s=>{if(s.users.some(u=>u.email===address))return;id=randomUUID();s.users.push({id,name,email:address,phone:text(body.phone,30),password:hash,role:'client',permissions:[],active:false,createdAt:now()});audit(s,null,'client.register',id);});if(id)await accessToken(id,'activate',address);return response({message:'Se o endereço estiver disponível, você receberá um link para ativar o acesso.'});}
 if(path==='/auth/recover'&&req.method==='POST'){await rate(req,'recover',8);if(!config().email)fail(503,'Recuperação por e-mail ainda não ativada. Contate a gestão.');const address=email(body.email);let user=(await store.read()).users.find(u=>u.email===address);if(!user&&address===email(env.OWNER_EMAIL)){user={id:randomUUID(),name:'Responsável MINDMORPHIA',email:address,password:'',role:'owner',active:false,permissions:[],createdAt:now()};await store.change(s=>{if(!s.users.some(u=>u.email===address))s.users.push(user);});user=(await store.read()).users.find(u=>u.email===address);}if(user)await accessToken(user.id,address===email(env.OWNER_EMAIL)&&(user.role!=='owner'||!user.active)?'owner':'reset',address);return response({message:'Se o e-mail estiver cadastrado, você receberá as instruções de acesso.'});}
 if(path==='/auth/activate'&&req.method==='POST'){await rate(req,'activate',12);const hash=await hashPassword(body.password);await store.change(s=>{const t=s.tokens.find(t=>t.hash===digest(String(body.token||''))&&Date.parse(t.expiresAt)>Date.now());if(!t)fail(400,'Link inválido ou expirado. Solicite outro.');const u=s.users.find(u=>u.id===t.userId);if(!u||u.suspended)fail(403,'Acesso suspenso.');if(t.purpose==='owner'&&u.email===email(env.OWNER_EMAIL))u.role='owner';u.password=hash;u.active=true;s.tokens=s.tokens.filter(x=>x.userId!==u.id);s.sessions=s.sessions.filter(x=>x.userId!==u.id);audit(s,u,'auth.activate',u.id);});return response({message:'Senha definida. Você já pode entrar.'});}
 if(path==='/auth/login'&&req.method==='POST'){await rate(req,'login',15);const s=await store.read();const u=s.users.find(u=>u.email===email(body.email));const valid=await checkPassword(body.password,u?.password);if(!u?.active||u.suspended||!valid)fail(401,'E-mail ou senha inválidos, ou acesso ainda não ativado.');const raw=token();await store.change(s=>{s.sessions=s.sessions.filter(x=>Date.parse(x.expiresAt)>Date.now());s.sessions.push({hash:digest(raw),userId:u.id,expiresAt:new Date(Date.now()+28800000).toISOString()});audit(s,u,'auth.login',u.id);});return response({user:safeUser(u)},200,{'Set-Cookie':cookie(raw,secure)});}
 if(path==='/auth/bootstrap'&&req.method==='POST'){await rate(req,'bootstrap',8);if(!env.OWNER_SETUP_HASH||digest(String(body.token||''))!==env.OWNER_SETUP_HASH||!(Date.parse(env.OWNER_SETUP_EXPIRES||'')>Date.now()))fail(403,'Link inicial inválido ou expirado.');requireValue(email(env.OWNER_EMAIL),'Proprietário ainda não configurado.');const hash=await hashPassword(body.password);await store.change(s=>{if(s.users.some(u=>u.role==='owner'&&u.active))fail(403,'A configuração inicial já foi concluída.');let u=s.users.find(u=>u.email===email(env.OWNER_EMAIL));if(!u){u={id:randomUUID(),email:email(env.OWNER_EMAIL),createdAt:now()};s.users.push(u);}Object.assign(u,{name:requireValue(text(body.name,100),'Informe seu nome.'),password:hash,role:'owner',permissions:[],active:true,suspended:false});s.sessions=s.sessions.filter(x=>x.userId!==u.id);audit(s,u,'owner.bootstrap',u.id);});return response({message:'Gestão ativada. Entre com seu e-mail e sua senha.'});}
 const s=await store.read();const user=await session(req,s);
 if(path==='/auth/me')return response({user:user?safeUser(user):null});
 if(!user)fail(401,'Entre para continuar.');
 const auth=p=>{if(!can(user,p))fail(403,'Sua conta não tem permissão para esta ação.');};
 if(path==='/auth/logout'&&req.method==='POST'){const raw=req.headers.get('cookie')?.match(/mm_session=([a-f0-9]{64})/)?.[1];await store.change(s=>{s.sessions=s.sessions.filter(x=>x.hash!==digest(raw||''));});return response({ok:true},200,{'Set-Cookie':cookie('',secure)});}
 if(path==='/profile'&&req.method==='POST'){await store.change(s=>{const u=s.users.find(u=>u.id===user.id);u.name=requireValue(text(body.name,100),'Informe seu nome.');u.phone=text(body.phone,30);audit(s,user,'profile.update',user.id);});return response({ok:true});}
 if(path==='/dashboard'&&req.method==='GET'){const projects=s.projects.filter(p=>p.userId===user.id||can(user,'projects'));const requests=s.requests.filter(r=>r.userId===user.id||can(user,'requests')).map(r=>visibleRequest(r,user));return response({user:safeUser(user),projects,requests,orders:s.orders.filter(o=>o.userId===user.id||can(user,'orders')),files:s.files.filter(f=>f.userId===user.id||can(user,'files')).map(({path,...f})=>f),notices:s.notices.filter(n=>n.userId===user.id||!n.userId||can(user,'notices')),clients:can(user,'clients')?s.users.map(safeUser):[],catalog:can(user,'catalog')?s.catalog:[],coupons:can(user,'catalog')?s.coupons:[],audit:user.role==='owner'?s.audit.slice(-100).reverse():[],services:config(),termsVersion});}
 if(path==='/quote'&&req.method==='POST')return response(quote(s,body));
 if(path==='/orders'&&req.method==='POST'){const q=quote(s,body);requireValue(body.accepted===true&&body.termsVersion===termsVersion,'Confirme as condições de contratação.');requireValue(text(body.brief,4000).length>=10,'Descreva seu projeto em pelo menos 10 caracteres.');const key=text(body.key,100);requireValue(/^[a-zA-Z0-9-]{16,100}$/.test(key),'Identificador inválido.');let result;await store.change(s=>{result=s.orders.find(o=>o.userId===user.id&&o.key===key);if(result)return;const verified=quote(s,body);result={id:randomUUID(),key,userId:user.id,...verified,paid:0,balance:verified.total,status:'aguardando_pagamento',brief:text(body.brief,4000),createdAt:now(),acceptance:{at:now(),version:termsVersion},payments:[]};s.orders.push(result);audit(s,user,'order.create',result.id);});return response({order:result},201);}
 const orderMatch=path.match(/^\/orders\/([a-f0-9-]+)\/(cancel|payment|reconcile)$/);
 if(orderMatch&&req.method==='POST'){const [,id,action]=orderMatch;own(s.orders.find(o=>o.id===id),user,'orders');if(action==='cancel'){await store.change(s=>{const o=s.orders.find(o=>o.id===id);o.cancellationAt=now();o.status=o.paid?'cancelamento_em_analise':'cancelado';audit(s,user,'order.cancel',id);});return response({message:'Cancelamento registrado. Valores pagos dependem da análise e do estorno pelo provedor.'});}
 if(!config().payment)fail(503,'Pagamento online ainda em ativação. Seu pedido permanece salvo.');
 if(action==='reconcile'){const o=s.orders.find(o=>o.id===id);const paymentId=String(body.paymentId||'');if(paymentId){requireValue(/^\d{1,30}$/.test(paymentId),'Pagamento inválido.');await syncPayment(paymentId,id);}else for(const p of o.payments.filter(x=>x.paymentId))await syncPayment(p.paymentId,id);return response({ok:true});}
 const attemptId=randomUUID();let order,attempt;await store.change(s=>{order=s.orders.find(o=>o.id===id);if(order.cancellationAt||order.balance<=0||['contestacao','estornado'].includes(order.status))fail(400,'Pedido não disponível para pagamento.');attempt=order.payments.find(p=>p.state==='pending'&&Date.parse(p.expiresAt)>Date.now());if(attempt?.url)return;if(attempt)fail(409,'Pagamento sendo preparado. Aguarde e tente novamente.');const amount=order.paid?order.balance:order.due;attempt={id:attemptId,amount,state:'pending',createdAt:now(),expiresAt:new Date(Date.now()+1800000).toISOString()};order.payments.push(attempt);});if(attempt.url)return response({url:attempt.url});
 try{const collector=await paymentCollector();const preference=await payment(env,'/checkout/preferences',{external_reference:order.id,statement_descriptor:'MINDMORPHIA',additional_info:`MINDMORPHIA | Pedido ${order.id} | Tentativa ${attempt.id}`,metadata:{brand:'MINDMORPHIA',channel:'mindmorphia-site',order_id:order.id,payment_attempt_id:attempt.id},items:[{id:attempt.id,title:`MINDMORPHIA ${order.items.map(x=>x.name).join(' + ')} | ${order.paid?'Saldo':order.mode==='deposit'?'Entrada 50%':'Integral'}`,quantity:1,unit_price:attempt.amount/100,currency_id:'BRL'}],payer:{email:user.email},back_urls:{success:`${origin}/cliente?pedido=${id}`,pending:`${origin}/cliente?pedido=${id}`,failure:`${origin}/cliente?pedido=${id}`},notification_url:`${origin}/api/webhooks/mercadopago`,auto_return:'approved',expires:true,expiration_date_from:attempt.createdAt,expiration_date_to:attempt.expiresAt,payment_methods:{installments:3}},attempt.id);requireValue(String(preference.collector_id)===collector,'Conta recebedora do checkout não confirmada.');const dest=checkoutUrl(preference.init_point);requireValue(dest,'Destino do pagamento inválido.');await store.change(s=>{const p=s.orders.find(o=>o.id===id).payments.find(p=>p.id===attempt.id);p.url=dest;p.preferenceId=preference.id;audit(s,user,'payment.preference',id);});return response({url:dest});}catch(e){await store.change(s=>{const p=s.orders.find(o=>o.id===id).payments.find(p=>p.id===attempt.id);p.state='failed';});throw e;}}
 if(path==='/requests'&&req.method==='POST'){const projectId=text(body.projectId,100);if(projectId)own(s.projects.find(p=>p.id===projectId),user,'requests');const id=randomUUID();const r={id,userId:user.id,projectId,type:text(body.type,100)||'Outras informações',subject:requireValue(text(body.subject,150),'Informe o assunto.'),description:requireValue(text(body.description),'Descreva a solicitação.'),status:'Aberta',priority:'Normal',classification:'Em análise',dueDate:'',assignedTo:'',createdAt:now(),history:[{at:now(),text:'Solicitação aberta.'}],messages:[],proposal:null};await store.change(s=>{s.requests.push(r);audit(s,user,'request.create',id);});return response({request:r},201);}
 const requestMatch=path.match(/^\/requests\/([a-f0-9-]+)\/(message|update|proposal|decision)$/);
 if(requestMatch&&req.method==='POST'){const [,id,action]=requestMatch;own(s.requests.find(r=>r.id===id),user,'requests');await store.change(s=>{const r=own(s.requests.find(r=>r.id===id),user,'requests');if(action==='message'){if(body.internal)auth('requests');r.messages.push({id:randomUUID(),author:user.name,text:requireValue(text(body.text),'Escreva uma mensagem.'),internal:!!body.internal,at:now()});}else if(action==='update'){auth('requests');const states=['Aberta','Triagem','Análise de escopo','Aguardando aceite','Execução','Revisão','Concluída','Não executável'];requireValue(states.includes(body.status),'Situação inválida.');r.status=body.status;r.classification=text(body.classification,150);r.dueDate=text(body.dueDate,30);r.assignedTo=text(body.assignedTo,100);r.priority=['Normal','Alta','Baixa'].includes(body.priority)?body.priority:'Normal';r.history.push({at:now(),text:`Situação: ${r.status}. Classificação: ${r.classification}. Prazo: ${r.dueDate||'Em análise'}. Responsável: ${r.assignedTo||'Em definição'}.`});}else if(action==='proposal'){auth('requests');const amount=Number(body.amount);requireValue(Number.isSafeInteger(amount)&&amount>=0&&amount<=100000000,'Valor inválido.');if(r.proposal)r.history.push({at:now(),text:`Proposta anterior ${r.proposal.id}: ${r.proposal.amount} centavos, ${r.proposal.decision||'sem decisão'}. Escopo: ${r.proposal.scope}`});r.proposal={id:randomUUID(),amount,scope:requireValue(text(body.scope),'Informe o escopo.'),dueDate:text(body.dueDate,30),createdAt:now(),decision:null};r.status='Aguardando aceite';r.history.push({at:now(),text:'Proposta enviada para aprovação.'});}else{if(r.userId!==user.id)fail(403,'Somente o cliente titular pode decidir.');requireValue(r.proposal&&r.proposal.id===body.proposalId&&!r.proposal.decision,'Proposta alterada ou já decidida. Atualize a página.');requireValue(['accepted','rejected'].includes(body.decision),'Decisão inválida.');r.proposal.decision=body.decision;r.proposal.decidedAt=now();r.status=body.decision==='accepted'?'Triagem':'Análise de escopo';r.history.push({at:now(),text:body.decision==='accepted'?'Cliente aprovou a proposta.':'Cliente rejeitou a proposta.'});}audit(s,user,`request.${action}`,id);});return response({ok:true});}
 if(path==='/files'&&req.method==='POST'){await rate(req,'upload',30);const requestId=text(body.requestId,100),projectId=text(body.projectId,100);let userId=user.id;if(requestId)userId=own(s.requests.find(r=>r.id===requestId),user,'files').userId;else if(projectId)userId=own(s.projects.find(r=>r.id===projectId),user,'files').userId;else fail(400,'Vincule o arquivo a um projeto ou solicitação.');if(projectId&&requestId){const project=own(s.projects.find(p=>p.id===projectId),user,'files');requireValue(project.userId===userId,'Os vínculos do arquivo devem pertencer ao mesmo cliente.');}const allowed={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','application/pdf':'pdf','text/plain':'txt'};const ext=allowed[body.type];requireValue(ext,'Envie PDF, PNG, JPG, WebP ou TXT.');requireValue(typeof body.data==='string'&&/^[A-Za-z0-9+/]*={0,2}$/.test(body.data),'Arquivo inválido.');const data=Buffer.from(body.data,'base64');requireValue(data.length>0&&data.length<=2*1024*1024,'O limite é 2 MB por arquivo.');const magic=data.subarray(0,12);const correct=ext==='pdf'?magic.subarray(0,5).toString()==='%PDF-':ext==='png'?magic.subarray(0,8).toString('hex')==='89504e470d0a1a0a':ext==='jpg'?magic[0]===255&&magic[1]===216&&magic[2]===255:ext==='webp'?magic.subarray(0,4).toString()==='RIFF'&&magic.subarray(8,12).toString()==='WEBP':!data.includes(0);requireValue(correct,'O conteúdo não corresponde ao formato informado.');const id=randomUUID(),path=`files/${userId}/${id}.${ext}`;await store.upload(path,data,body.type);await store.change(s=>{s.files.push({id,userId,projectId,requestId,name:text(body.name,160).replace(/[\r\n"\\/]/g,'_')||`arquivo.${ext}`,type:body.type,size:data.length,path,createdAt:now()});audit(s,user,'file.upload',id);});return response({id},201);}
 const fileMatch=path.match(/^\/files\/([a-f0-9-]+)$/);if(fileMatch&&req.method==='GET'){const f=own(s.files.find(f=>f.id===fileMatch[1]),user,'files');const file=await store.download(f.path);if(!file)fail(404,'Arquivo não encontrado.');return new Response(file.data,{headers:{'Content-Type':f.type,'Content-Disposition':`${url.searchParams.get('preview')==='1'&&f.type.startsWith('image/')?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
 if(path==='/admin/catalog'&&req.method==='POST'){auth('catalog');const price=Number(body.price);requireValue(Number.isSafeInteger(price)&&price>=100&&price<=100000000,'Preço inválido.');const item={id:text(body.id,80)||randomUUID(),name:requireValue(text(body.name,100),'Informe o nome.'),category:text(body.category,80)||'Serviços',description:text(body.description,500),scope:text(body.scope,1000),price,active:!!body.active};await store.change(s=>{const i=s.catalog.findIndex(x=>x.id===item.id);if(i>=0)s.catalog[i]=item;else s.catalog.push(item);audit(s,user,'catalog.save',item.id);});return response({ok:true});}
 if(path==='/admin/coupons'&&req.method==='POST'){auth('catalog');const code=text(body.code,40).toUpperCase();const percent=Number(body.percent);requireValue(/^[A-Z0-9_-]{3,40}$/.test(code)&&Number.isFinite(percent)&&percent>0&&percent<=50,'Cupom inválido.');const expiresAt=text(body.expiresAt,30);requireValue(!expiresAt||Number.isFinite(Date.parse(expiresAt)),'Data inválida.');await store.change(s=>{const item={code,percent,expiresAt,active:!!body.active};const i=s.coupons.findIndex(x=>x.code===code);if(i>=0)s.coupons[i]=item;else s.coupons.push(item);audit(s,user,'coupon.save',code);});return response({ok:true});}
 if(path==='/admin/projects'&&req.method==='POST'){auth('projects');const userId=text(body.userId,100);requireValue(s.users.some(u=>u.id===userId&&u.role==='client'),'Cliente inválido.');const id=text(body.id,100)||randomUUID();await store.change(s=>{let p=s.projects.find(p=>p.id===id);if(!p){p={id,userId,orderId:'',createdAt:now(),history:[]};s.projects.push(p);}requireValue(p.userId===userId,'O titular de um projeto existente não pode ser alterado.');p.name=requireValue(text(body.name,150),'Informe o nome.');p.scope=text(body.scope);p.status=text(body.status,100)||'Materiais pendentes';p.dueDate=text(body.dueDate,30);p.stages=Array.isArray(body.stages)?body.stages.slice(0,30).map(x=>({name:text(x.name,120),done:!!x.done})):[];p.history.push({at:now(),text:`Projeto atualizado: ${p.status}. Prazo: ${p.dueDate||'Em análise'}.`});audit(s,user,'project.save',id);});return response({ok:true});}
 if(path==='/admin/invite'&&req.method==='POST'){auth('clients');const address=email(body.email);requireValue(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address),'E-mail inválido.');const role=body.role==='staff'?'staff':'client';if(role==='staff'&&user.role!=='owner')fail(403,'Somente o proprietário pode convidar a equipe.');let id;await store.change(s=>{if(s.users.some(u=>u.email===address))fail(400,'E-mail já cadastrado. Use recuperação de acesso.');id=randomUUID();s.users.push({id,email:address,name:requireValue(text(body.name,100),'Informe o nome.'),phone:text(body.phone,30),role,permissions:role==='staff'?(body.permissions||[]).filter(p=>permissions.includes(p)):[],password:'',active:false,createdAt:now()});audit(s,user,'user.invite',id);});if(config().email){await accessToken(id,'activate',address);return response({ok:true});}const raw=token();await store.change(s=>s.tokens.push({hash:digest(raw),userId:id,purpose:'activate',expiresAt:new Date(Date.now()+3600000).toISOString()}));return response({activationUrl:`${origin}/acesso?token=${raw}`,message:'Link individual válido por uma hora. Compartilhe diretamente com a pessoa cadastrada.'});}
 if(path==='/admin/recovery'&&req.method==='POST'){auth('clients');const u=s.users.find(u=>u.id===body.id);requireValue(u&&!u.suspended,'Conta não disponível.');if(u.role!=='client'&&user.role!=='owner')fail(403,'Somente o proprietário pode recuperar acesso da equipe.');const raw=token();await store.change(s=>{s.tokens=s.tokens.filter(t=>t.userId!==u.id);s.tokens.push({hash:digest(raw),userId:u.id,purpose:'reset',expiresAt:new Date(Date.now()+3600000).toISOString()});audit(s,user,'auth.recovery-issued',u.id);});return response({activationUrl:`${origin}/acesso?token=${raw}`,message:'Confirme a identidade do titular por seu canal de atendimento antes de compartilhar este link individual.'});}
 if(path==='/admin/team'&&req.method==='POST'){if(user.role!=='owner')fail(403,'Somente o proprietário pode gerenciar permissões.');await store.change(s=>{const u=s.users.find(u=>u.id===body.id&&u.role!=='owner');requireValue(u,'Conta não encontrada.');u.permissions=(Array.isArray(body.permissions)?body.permissions:[]).filter(p=>permissions.includes(p));u.suspended=!!body.suspended;if(u.suspended)s.sessions=s.sessions.filter(x=>x.userId!==u.id);audit(s,user,'team.permissions',u.id);});return response({ok:true});}
 if(path==='/admin/notices'&&req.method==='POST'){auth('notices');const userId=text(body.userId,100);requireValue(!userId||s.users.some(u=>u.id===userId&&u.role==='client'),'Destinatário inválido.');await store.change(s=>{const n={id:randomUUID(),userId,title:requireValue(text(body.title,150),'Informe o título.'),text:requireValue(text(body.text),'Escreva o comunicado.'),createdAt:now(),readBy:[]};s.notices.push(n);audit(s,user,'notice.publish',n.id);});return response({ok:true});}
 if(path==='/notices/read'&&req.method==='POST'){await store.change(s=>{const n=s.notices.find(n=>n.id===body.id&&(!n.userId||n.userId===user.id));requireValue(n,'Comunicado não encontrado.');if(!n.readBy.some(r=>r.userId===user.id))n.readBy.push({userId:user.id,at:now()});});return response({ok:true});}
 if(path==='/admin/backup'&&req.method==='POST'){if(user.role!=='owner')fail(403,'Somente o proprietário pode criar backup.');if(!store.backup)fail(503,'Backup disponível no ambiente publicado.');await store.backup(s);await store.change(s=>audit(s,user,'backup.create','private'));return response({message:'Backup privado criado. A restauração exige procedimento técnico controlado.'});}
 fail(404,'Recurso não encontrado.');
 }catch(e){const status=e.status|| (e.message?.includes('configurad')?503:400);return response({error:status>=500?'Serviço temporariamente indisponível. Contate a gestão.':e.message||'Não foi possível concluir.'},status);}
 };
}
